# ruff.toml
target-version = "py311"

[lint]
select = ["E", "F", "W", "I"]
ignore = [
  "F401",
  "F405",
  "F821",
]
# Remove or replace the following line:
# fix = true

[format]
quote-style = "preserve"
line-ending = "auto"