name: CI

permissions:
  contents: read

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint-and-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install mpy-cross

      - name: MicroPython syntax check (mpy-cross)
        run: |
          # Compile MicroPython files to .mpy as a syntax check
          # Add more .py files if you create modules
          test -f main.py && mpy-cross main.py
